title: linnal Blog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I learn from the community and love to share what I have learned back.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://linnal.github.io" # the base hostname & protocol for your site
twitter_username: ErindaJaupi
github_username:  linnal

# Build settings
markdown: kramdown

emoji:
  src: "/assets/images/"

paginate: 10
excerpt_separator: <!--more-->

gems:
  - jemoji
  - jekyll-paginate
